name: Build APK file
on:
  push:
    paths:
      - 'pubspec.yaml'
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9'
    - run: flutter build apk --release
    - run: gh release create build/app/outputs/flutter-apk/app-release.apk
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
